### ISSUE TITLE
[Question] How to work Multi-Stage?

### ISSUE THREAD

**Issue by Kristinita** [fwph/codepresenter#6]
### Briefly

I can not understand, how to work Multi-Stage in Code Presenter. Maybe because I know English bad. It would be nice, if you make screencast or show real example.

### Did not help

My folder structure:

    |— SourceFolder
      |— Sasha.py
      |— NextFolder
        |— Sasha.md

For example, Right Click to `SourceFolder` → `CodePresenter Actions` → `Configure` → `Set Source Folder`.

Examples of my attempts:

1. Right click to `SourceFolder` → `Next Stage` → I get stack trace:

```python
command: code_presenter_next_stage
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "codepresenter in E:\Sublime Text 3\Data\Installed Packages\CodePresenter.sublime-package", line 483, in run
  File "codepresenter in E:\Sublime Text 3\Data\Installed Packages\CodePresenter.sublime-package", line 289, in next_stage
ValueError: 'E:\\Киролайна\\SourceFolder' is not in list
```

2. Right click to `SourceFolder` → `CodePresenter Actions` → `Run Presentation Stage` → I get `Sasha.py` and `Sasha.md` presentations.  
Next right click to `SourceFolder` → `CodePresenter Actions` → `Next Stage` → I get same stack trace. Right click to `NextFolder` → `CodePresenter Actions` → `Next Stage` → I get same stack trace.

Thanks.

**Comment by Kristinita** [comment]
<details>
<summary>
**Click here to see full log.**</summary>

	For example, Right Click to `SourceFolder` → `CodePresenter Actions` → `Configure` → `Set Source Folder`.

	Examples of my attempts:

	1. Right click to `SourceFolder` → `Next Stage` → I get stack trace:

</details>

**Comment by fwph** [comment]
Thanks -- this is a poorly documented and unclear issue. 

Multi-stage presentations only work with directories. All of the files you want to present must be in a subdirectory of the source folder. If you run `CodePresenter` -> `Reset Code Presentation` and then start the presentation with `CodePresenter` -> `Next Stage` it should work. 

If this works for you, please leave this issue open; I should clarify this usage (and make it better).

**Comment by Kristinita** [comment]
> All of the files you want to present must be in a subdirectory of the source folder. If you run `CodePresenter -> Reset Code Presentation` and then start the presentation with `CodePresenter -> Next Stage` it should work.

But If I run `CodePresenter → Reset Code Presentation` and then start the presentation with `CodePresenter → Run Presentation Stage` it also work.

Thanks.

**Comment by fwph** [comment]
Aha, I understand now.

When you use the sidebar actions, you need to right click on a particular **subfolder** of the sourcefolder (that is, `NextFolder`, in your example) with `Run Presentation Stage`. The `Run Presentation Stage` action is meant to run with a particular subfolder of `sourcefolder`, not to start a multi-stage presentation. It looks like I did not write any checks to make sure that CP thinks the folder you run it on is actually a sub-stage. 

So if you put `Sasha.py` into a folder called `firstfolder`, right click `Run Presentation Stage` on `firstfolder`, and then run `Next Stage`, it should work.  Note that the command palette `CodePresenter: Next Code Stage` action is equivalent to the sidebar `Next Stage` action.

**Comment by fwph** [comment]
(The more understandable behavior here would be to treat the files at the top level of `SourceFolder` as code stages like the subfolders; that will take a bit more effort, but seems like a reasonable change)

**Comment by Kristinita** [comment]
@fwph, what I do wrong?

![Multi-Stage](http://i.imgur.com/KjQnVul.gif)

Thanks.
