### ISSUE TITLE
[Bug] AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by Kristinita** [fwph/codepresenter#7]
### 1. Summary

I get stack trace in console, if I use `Goto Anything...` panel (<kbd>Ctrl+P</kbd> by default in Windows).

### 2. Expected behavior

No stack trace in console.

### 3. Actual behavior

```python
chr evt: r (0x72)
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "E:\Sublime Text 3\sublime_plugin.py", line 428, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "codepresenter in E:\Sublime Text 3\Data\Installed Packages\CodePresenter.sublime-package", line 576, in on_load
  File "codepresenter in E:\Sublime Text 3\Data\Installed Packages\CodePresenter.sublime-package", line 119, in find_view
  File "codepresenter in E:\Sublime Text 3\Data\Installed Packages\CodePresenter.sublime-package", line 111, in get_project
AttributeError: 'NoneType' object has no attribute 'id'
```

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I open `Goto Anything...` panel → I print any text in panel → if previewed file change for me, I get error in console.

### 5. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by fwph** [comment]
This should be addressed in 1.2.3 -- let me know if the problem goes away. I believe it to have been harmless, but annoying to see in the console. If confirmed that it no longer appears (though it may generate additional noise in the console), I'll adjust the verbosity in another tiny version.

**Comment by Kristinita** [comment]
@fwph, now if I print text in Goto Anything panel, I constantly get in console:

> CodePresenter: Got an attributeerror. Probably not my view

Is it possible to remove this output?

Thanks.

**Comment by Kristinita** [comment]
Now problem not reproduced for me. Thank you!
